# -*- mode: ruby -*-
# vi: set ft=ruby :


ENV["LC_ALL"] = "en_US.UTF-8"


if ENV['HOSTNAME'] then
    HOSTNAME = ENV['HOSTNAME']
else
    HOSTNAME = "ubuntu"
end

Vagrant.configure(2) do |config|

  # Ubuntu 22.04 box with osquery
  config.vm.define ENV['HOSTNAME'] do |ubuntu|
    ubuntu.vm.box = "labrat_golden"
    ubuntu.vm.hostname = HOSTNAME
    ubuntu.vm.synced_folder ".", "/vagrant", disabled: true

    #ubuntu.vm.network :private_network, :auto_network => true
    #ubuntu.vm.network "private_network", type: "dhcp"

    ubuntu.vm.provision "shell", inline: 'echo "Restart filebeat to refresh hostname"'
    ubuntu.vm.provision "shell", inline: 'systemctl restart filebeat'
    ubuntu.vm.provision "shell", inline: 'echo "About to install pipi package"'
    ubuntu.vm.provision "shell", privileged: false do |s|
        s.inline = "pip install $1;sleep 20;"
        s.args   = [ENV['PACKAGE_NAME_INSTALL']]
    end

    ubuntu.vm.provision "shell", inline: 'echo "About to import pipi package"'
    ubuntu.vm.provision "shell", privileged: false do |s|
        s.inline = <<-SCRIPT
                    python3 -c"
import time
try:
    import #{ENV['PACKAGE_NAME_IMPORT']}
    time.sleep(20)
except:
    pass
"
    SCRIPT
        s.args   = [ENV["PACKAGE_NAME_IMPORT"]]
    end

    ubuntu.vm.provider 'virtualbox' do |vbox|
        vbox.name = HOSTNAME
        vbox.memory = 2048
        vbox.cpus = 2
        vbox.gui = true
        vbox.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        vbox.customize ['modifyvm', :id, '--accelerate3d', 'off']
        vbox.customize ['modifyvm', :id, '--graphicscontroller', 'vmsvga']
        # vbox.customize ['modifyvm', :id, '--graphicscontroller', 'vboxvga']
        vbox.customize ['modifyvm', :id, '--hwvirtex', 'on']
        vbox.customize ['modifyvm', :id, '--ioapic', 'on']
        vbox.customize ['modifyvm', :id, '--vram', '128']
        vbox.customize ['modifyvm', :id, '--audio', 'none']
    end

   ubuntu.vm.provider :libvirt do |libvirt|
        libvirt.memory = 1024
        libvirt.cpus = 1
        #libvirt.graphics_port = 5901
        #libvirt.graphics_ip = '0.0.0.0'
        libvirt.video_type = 'qxl'
  end

  end

end
