input {
  beats {
    port => 5044
  }
}

filter {
  mutate {
    add_field => { "hostname" => "%{[fields][hostname]}" }
  }
}

output {
  file {
    path => "<ABS PATH>/%{[hostname]}-%{+yyyy-MM-dd}.log"
    codec => "line"
  }
}